spring.application.name=jobs24

spring.datasource.url=jdbc:mysql://localhost:3306/jobs24
spring.datasource.username=root
spring.datasource.password=Jyoti100@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true